services:
  forum:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: forum_app
    restart: always
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 3333

      PGHOST: db
      PGUSER: user
      PGPASSWORD: password
      PGDATABASE: mini_forum
      PGPORT: 5432

    depends_on:
      - db

    volumes:
      - ./src:/app/src
      - /app/node_modules

  db:
    image: postgres:17
    container_name: forum_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mini_forum
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: elestio/pgadmin:latest
    container_name: forum_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 2@2.com
      PGADMIN_DEFAULT_PASSWORD: 22
    ports:
      - "2020:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data2:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data2:
